title: 《梦里山河》游戏
description: 《梦里山河》游戏策划Wiki
theme: just-the-docs

url: https://mlshproject.github.io

aux_links:
  Github主页: https://github.com/mlshproject/mlshproject.github.io

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.3"

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Highlight
    color: blue